### ISSUE TITLE
jwplayer causes fatal error in Moodle 3.5.1

### ISSUE THREAD

**Issue by multiplexer2** [lucisgit/moodle-media_jwplayer#10]
After an upgrade from Moodle 3.3 to 3.5, a fatal error is occuring while jwplayer is processing a video tag. The logs are full of messages like this:

Default exception handler: Exception - String could not be parsed as XML Debug: \nError code: generalexceptionmessage\n* line 97 of /media/player/jwplayer/classes/plugin.php: Exception thrown\n* line 97 of /media/player/jwplayer/classes/plugin.php: call to SimpleXMLElement->__construct()\n* line 266 of /media/classes/manager.php: call to media_jwplayer_plugin->embed()\n* line 193 of /filter/mediaplugin/filter.php: call to core_media_manager->embed_alternatives()\n* line 231 of /filter/mediaplugin/filter.php: call to filter_mediaplugin->embed_alternatives()\n* line 110 of /filter/mediaplugin/filter.php: call to filter_mediaplugin->process_media_tag()\n* line 176 of /lib/filterlib.php: call to filter_mediaplugin->filter()\n* line 218 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()\n* line 1279 of /lib/weblib.php: call to filter_manager->filter_text()\n* line 1025 of /course/format/renderer.php: call to format_text()\n* line 238 of /course/format/renderer.php: call to format_section_renderer_base->format_summary_text()\n* line 912 of /course/format/renderer.php: call to format_section_renderer_base->section_header()\n* line 57 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()\n* line 280 of /course/view.php: call to require()\n, referer: /lms/course/edit.php

Example of video tag causing this error:
(This is the content of $options[core_media_manager::OPTION_ORIGINAL_TEXT] on line 97 of /media/player/jwplayer/classes/plugin.php)

```
<video controls="true">
<source src="http://streaming.blah.com:1935/vod/mp4:FS2COF061_2017-03-27a.mp4/playlist.m3u8">
<source src="http://streaming.blah.com:1935/vod/mp4:FS2COF061_2017-03-27a.mp4/Manifest">
<source src="http://streaming.blah.com:1935/vod/mp4:FS2COF061_2017-03-27a.mp4/playlist.m3u8">
<source src="rtsp://streaming.blah.com:1935/vod/FS2COF061_2017-03-27a.mp4">
<source src="rtmp://streaming.blah.com:1935/vod/FS2COF061_2017-03-27a.mp4">
Your browser does not support the video tag, so you can not view the video file named "FS2COF061_2017-03-27a.mp4".</video>
```

**Comment by kabalin** [comment]
Thanks for issue report. @jproctor do you have any thoughts on this?

**Comment by multiplexer2** [comment]
A HTML5 video element with self closing source tags is not valid XML, so it cannot be parsed as is with SimpleXMLElement.  XML does not allow self closing tags.

**Comment by kabalin** [comment]
Addressed in https://github.com/lucisgit/moodle-media_jwplayer/commit/a49495f2228a97436a2c478fd3a5b2f5f55b7761

**Comment by kabalin** [comment]
Fixed in https://github.com/lucisgit/moodle-media_jwplayer/releases/tag/moodle-media_jwplayer_7-0.3
