### ISSUE TITLE
Display Options when embedding a video are ignored

### ISSUE THREAD

**Issue by jonlan** [lucisgit/moodle-media_jwplayer#12]
We have the following system environment:
- JW Player Plugin: media_jwplayer, 7-0.3 for Moodle 3.5+, JW7 CDN 7.12.13) 2018082400
- Moodle, Moodle 3.6.4+ (Build: 20190519)
- Self-Hosted JWPlayer 7.12.13

We have the following Problems:
- We cannot crate a preview image, the "Thumbnail URL" is ignored.
- The Title "tooltip" is ignored
- The filename of the movie file is displayed and there is only a black screen.
- Atto Editor

With the standard JSPlayer of Moodle it works.

**Comment by jonlan** [comment]
![Capture](https://user-images.githubusercontent.com/4759915/62190414-98ef3280-b371-11e9-91f8-a0202fbea586.PNG)

**Comment by jonlan** [comment]
![Capture2](https://user-images.githubusercontent.com/4759915/62190478-bae8b500-b371-11e9-8b47-fbd8458ffc6e.PNG)

**Comment by kabalin** [comment]
Hi @jonlan, thanks for report. Most of issues were addressed already on master branch (https://github.com/lucisgit/moodle-media_jwplayer/commits/master), but we did not release. May be it is time to do it in fact. Is there a chance you can test it against master and let me know if any of those issues are still there? Thanks!

**Comment by jonlan** [comment]
Dear Ruslan

Thank you for the Info. I successfully tested the master version and found no issues. I think you can release it.

Kind regards,
Jonas Lanz

**Comment by kabalin** [comment]
Thanks @jonlan, I will try to release within next few days.

**Comment by jonlan** [comment]
Hi Ruslan

Could you please release it before next week, 12.08.2019, though we are planning an update.

Thanks,
Jonas

**Comment by kabalin** [comment]
@jonlan I am going to release later today.

**Comment by kabalin** [comment]
Version 0.4 has been released: https://github.com/lucisgit/moodle-media_jwplayer/releases/tag/moodle-media_jwplayer_7-0.4 I will update it in Moodle plugins directory as well.

**Comment by kabalin** [comment]
Published on Moodle plugins dir: https://moodle.org/plugins/pluginversions.php?plugin=media_jwplayer
