### ISSUE TITLE
Feature - Set Playback Rate

### ISSUE THREAD

**Issue by mj445** [lucisgit/moodle-media_jwplayer#13]
Hello, I believe I was advised to submit this request here. 

Thank you for this awesome plugin! We would love to use it exclusively, but since we offer ASL courses, we need the JW Player set playback rate (slow motion) feature to be able to be added to the video player controls. 

More information here: https://developer.jwplayer.com/jw-player/demos/advanced/set-playback-rate/

We currently use the Video Easy Filter plugin with a JW Player template to achieve what we need, but would love to switch to this more native plugin. 

Please consider adding the set playback rate feature to your plugin - it would be a great addition! Thank you!

**Comment by mj445** [comment]
I would be willing to fund this enhancement. :) Please let me know if this is possible.

**Comment by kabalin** [comment]
Fixed in 7-0.5 release.
