### ISSUE TITLE
Always: Cannot load M3U8: Crossdomain access denied, Only except allowing guest login enrollment method

### ISSUE THREAD

**Issue by fishfree** [lucisgit/moodle-media_jwplayer#3]
Even I use the admin user, whether CDN or local hosted, JW player always failed to load M3U8 file with this error message.
I search and followed [this tip](https://support.jwplayer.com/customer/portal/articles/1403679-crossdomain-file-loading), but of no vail.

**Comment by kabalin** [comment]
Hello, this issue has nothing to do with JW Player plugin. Say, you are using moodle on SITE-A, and adding the video via URL from SITE-B. SITE-B should list SITE-A in crossdomain.xml:
`allow-access-from domain="*.SITE-A.com"`

**Comment by fishfree** [comment]
@kabalin I confirmed that the server hosting m3u8 files indeed has a crossdomain.xml:
```
<cross-domain-policy>
   <allow-access-from domain="*"/>
</cross-domain-policy>
```

**Comment by kabalin** [comment]
In this case it is difficult to expalin why player show the error? Is that m3u8 file publically available, so I can test? Also, what if you embed URL pointing at https://content.jwplatform.com/manifests/yp34SRmf.m3u8 for example, so you see the same error?

**Comment by fishfree** [comment]
@kabalin I can play your m3u8 without problem. So strange...

**Comment by kabalin** [comment]
In which case the issue is definitely with the hosting where your m3u8 is located.

**Comment by fishfree** [comment]
@kabalin Yes. When I use the client's Shibboleth account to login in Moodle, then JW player can play their m3u8.

Thank you!
