### ISSUE TITLE
trying to get new player to work with red5 server

### ISSUE THREAD

**Issue by mmatthes** [lucisgit/moodle-media_jwplayer#5]
I have a working moodle 2.62 with media filters Streaming, media filter (RTMP)turned on working accessing files to stream from Red5 server and allows files to be streamed from the red 5 server URL../oflaDemo/streams/ and any sub-directory i create, for the past 4 years.  But when i have upgraded to moodle 3.2  with JW Player media_jwplayer enabled and player and files downloaded, installed and working but now it only allows files to be played from the red 5 server URL../oflaDemo directory and not anything under that point, it act like it isnt seeing anything past that point.  Nothing has be changed on the Red5 server and it still works with the moodle 2.6.2 server.

**Comment by kabalin** [comment]
Hi, thanks for reporting the issue. RTMP URL may require specifying content type prefix in some cases, so that player would know where base streaming server URL ends, and where stream name (with path) begins. Sometimes, when steam name does not contain any path, player may figure out how to handle it without prefix, but normally it is required.

Try this one:
rtmp://red5.iowacentral.edu/oflaDemo/mp4:autovideos/WasteSparkCoilTesting.mp4

**Comment by mmatthes** [comment]
what about flv the same?

**Comment by mmatthes** [comment]
how about showing or turning off the closed caption in the viewer?

**Comment by kabalin** [comment]
> what about flv the same?

Yes, but prefix needs to be flv. If stream name does not contain "path", then it may work in JW Player without prefix, as you found already. e.g. rtmp://red5.iowacentral.edu/oflaDemo/somestream.mp4

> how about showing or turning off the closed caption in the viewer?

Not sure what you mean. The title?

**Comment by mmatthes** [comment]
Is there a way if the closed caption is included in the mp4 file, to turn that off/on from the player or an option that can provide a toggle to do that?

**Comment by kabalin** [comment]
Ah, you mean subtitles. No, it is not possible.

**Comment by kabalin** [comment]
If subtitles are hosted separately though, you may add them in the URL:
`<a href="http://content.jwplatform.com/videos/3XnJSIm4-kNspJqnJ.mp4" data-jwplayer-subtitles="English: http://assets-jp.jwpsrv.com/tracks/2UEDrDhv.txt">test subtitles</a>`

In fact, I have just realised this does not work for some reason at Moodle 3.3 at least. Will create a ticket.
