### ISSUE TITLE
data-jwplayer-* URL attributes are ignored in Moodle 3.3 onwards.

### ISSUE THREAD

**Issue by kabalin** [lucisgit/moodle-media_jwplayer#6]
As found while commenting on #5 It seems like data-jwplayer-* attributes are not retrieved properly for using in setup JSON object. e.g.
`<a href="http://content.jwplatform.com/videos/3XnJSIm4-kNspJqnJ.mp4" data-jwplayer-subtitles="English: http://assets-jp.jwpsrv.com/tracks/2UEDrDhv.txt" data-jwplayer-description="some description">test subtitles</a>`

is rendered as:
`require(["media_jwplayer/jwplayer"], function(amd) { amd.setupPlayer({"playerid":"media_jwplayer_media_random5af1a61a44c1987","setupdata":{"playlist":[{"sources":[{"file":"https:\/\/content.jwplatform.com\/videos\/3XnJSIm4-kNspJqnJ.mp4"}],"title":"3XnJSIm4-kNspJqnJ.mp4"}],"width":400,"height":225},"logcontext":1618506,"logevents":["play","pause","complete"]}); });`

**Comment by jproctor** [comment]
The embed code is looking for `$options['htmlattributes']`, but `$options` only has keys `originaltext`, `trusted`, and `embedorblank`, which are created in /filter/mediaplugin/filter.php near this comment:

> ```php
> // NOTE: Options are not passed through from filter because the 'embed'
> // code does not recognise filter options (it's a different kind of
> // option-space) as it can be used in non-filter situations.
> ```

That said, I think I know how to fix it. PR forthcoming.

**Comment by kabalin** [comment]
Great, thanks @jproctor!
